'use strict';
window.MidasAccounts={
 mount(client,gate,msg){
  const card=gate.querySelector('.cloud-card');
  card.querySelector('h2').textContent='Welcome to M.I.D.A.S.';
  card.querySelector('h2+p').textContent='Sign in with your email and password. New team members request approval once.';
  const password=card.querySelector('#password-option');password.open=true;password.querySelector('summary').textContent='Sign in';password.querySelector('.note').textContent='Already approved? Sign in normally. No new approval is needed.';
  const emailForm=card.querySelector('#cloud-login'),emailDetails=document.createElement('details');emailDetails.innerHTML='<summary>Email-link sign-in</summary>';emailForm.before(emailDetails);emailDetails.append(emailForm);
  const register=document.createElement('details');register.id='register-option';register.innerHTML='<summary>Create account / request access</summary><form id="registration-form"><label for="registration-name">Your name</label><input id="registration-name" required maxlength="100" autocomplete="name"><label for="registration-email">Email address</label><input id="registration-email" type="email" required autocomplete="email"><label for="registration-password">Choose a password (at least 10 characters)</label><input id="registration-password" type="password" required minlength="10" autocomplete="new-password"><label for="registration-confirm">Confirm password</label><input id="registration-confirm" type="password" required minlength="10" autocomplete="new-password"><label for="registration-note">Message to the owner (optional)</label><textarea id="registration-note" maxlength="500" placeholder="Your project group or how the owner knows you"></textarea><button class="primary">Create account & request access</button></form><p class="note">Creating an account does not give access to the project. The owner must approve you first. Passwords are handled by Supabase and are never visible to the owner.</p>';password.after(register);
  register.querySelector('form').onsubmit=async e=>{e.preventDefault();const name=document.querySelector('#registration-name').value.trim(),email=document.querySelector('#registration-email').value.trim(),password=document.querySelector('#registration-password').value,confirm=document.querySelector('#registration-confirm').value,note=document.querySelector('#registration-note').value.trim(),b=e.target.querySelector('button');if(password!==confirm){msg('The passwords do not match.');return;}b.disabled=true;msg('Creating your account…');try{const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name,access_note:note},emailRedirectTo:new URL('overview.html',location.href).href}});if(error)throw error;if(data.session){const request=await client.rpc('of_request_access',{p_display_name:name,p_note:note});if(request.error)throw Error('Your account was created, but the request could not be submitted: '+request.error.message+'. Sign in again to retry.');location.reload();}else{msg('If this is a new account, check your confirmation email and then sign in to submit your access request. If no email arrives, ask the owner to finish the registration setup. Existing account? Use Sign in.');}}catch(err){msg(err.message);}finally{document.querySelector('#registration-password').value='';document.querySelector('#registration-confirm').value='';b.disabled=false;}};
 },
 async waiting(client,gate,msg,user){
  gate.querySelectorAll('form,details').forEach(e=>e.hidden=true);
  const message=document.createElement('div');message.className='pending-access';const name=String(user.user_metadata?.display_name||user.email||'Team member').slice(0,100),note=String(user.user_metadata?.access_note||'').slice(0,500);
  let request;try{const {data,error}=await client.rpc('of_request_access',{p_display_name:name,p_note:note});if(error)throw error;request=data;}catch(e){msg('The owner needs to finish the Team approval database setup. Your account has no project access yet. '+e.message);return;}
  const state=Array.isArray(request)?request[0]:request;const heading=document.createElement('h3');heading.textContent=state.status==='pending'?'Waiting for owner approval':state.status==='rejected'?'Access request declined':state.status==='revoked'?'Project access revoked':'Approval needs attention';const p=document.createElement('p');p.textContent=state.status==='pending'?'Your request has been sent. Once the owner approves you, you can sign in anytime without asking again.':'Contact your project owner if you believe your access should change.';const email=document.createElement('p');email.textContent=user.email;const refresh=document.createElement('button');refresh.textContent='Check approval status';refresh.onclick=()=>location.reload();message.append(heading,p,email,refresh);gate.querySelector('.cloud-card').insertBefore(message,document.querySelector('#cloud-message'));msg('No project data is available until approval.');
  const timer=setInterval(async()=>{const {data,error}=await client.rpc('of_my_role');if(!error&&data){clearInterval(timer);location.reload();}},15000);
 }
};
