'use strict';
(async function(){
 const LIB='orbital-foundry-cloud-library-v1',DES='orbital-foundry-cloud-design-v1',DRAFT='orbital-foundry-cloud-unsaved-v1';
 const main=document.querySelector('main'),aside=document.querySelector('aside');
 const gate=document.createElement('section');gate.id='cloud-gate';gate.innerHTML='<div class="cloud-card"><p class="eyebrow">MIDAS / TEAM ACCESS</p><h2>Your shared design workspace</h2><p>Sign in with your approved team email. We’ll send you a sign-in link.</p><form id="cloud-login"><label for="cloud-email">Email address</label><input id="cloud-email" type="email" autocomplete="email" required placeholder="you@example.com"><button class="primary">Email me a sign-in link</button></form><details id="password-option"><summary>Sign in with a password instead</summary><form id="cloud-password-login"><label for="password-email">Approved email</label><input id="password-email" type="email" autocomplete="username" required><label for="password-value">Password</label><input id="password-value" type="password" autocomplete="current-password" required><button class="primary">Sign in</button></form><p class="note">For approved accounts created by your project owner. This route does not send email.</p></details><p id="cloud-message" class="cloud-message" role="status">Connecting…</p><button id="cloud-reset" hidden>Sign out / use another account</button></div>';document.body.append(gate);main.inert=true;aside.inert=true;
 const msg=t=>document.querySelector('#cloud-message').textContent=t;
 if(!window.supabase){msg('The sign-in library could not load. Refresh this page when you are online.');return;}
 const client=window.supabase.createClient(ORBITAL_CLOUD_CONFIG.url,ORBITAL_CLOUD_CONFIG.publishableKey);
 MidasAccounts.mount(client,gate,msg);
 let role=null,rows=new Map(),optimistic=new Map(),queue=Promise.resolve(),pending=0,failed=false,dirty=false,ready=false,refreshNeeded=false,refreshing=false,pointerDown=false;
 const key=(kind,id)=>kind+'/'+id,clone=v=>structuredClone(v),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
 const bar=document.createElement('div');bar.id='cloud-bar';bar.innerHTML='<span id="cloud-status" role="status">Connecting…</span><button id="cloud-reload">Load latest</button><button id="cloud-history-button">History & restore</button><button id="cloud-draft">Export current draft</button><button id="cloud-logout">Sign out</button>';main.prepend(bar);
 const status=t=>document.querySelector('#cloud-status').textContent=t;
 function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 function currentExport(){let research={},designData={};try{research=JSON.parse(localStorage.getItem(LIB))||{};designData=JSON.parse(localStorage.getItem(DES))||{};}catch{}if(ready){if(['presentations','team','industry'].includes(document.body.dataset.page)){}else if(document.body.dataset.page)designData=design;else research=state;}const formDraft=[...document.querySelectorAll('main input,main textarea,main select,dialog input,dialog textarea,dialog select')].filter(e=>e.type!=='file'&&e.type!=='password').map(e=>({field:e.name||e.id,value:e.value}));return {...research,design:designData,decks:window.MidasPresentations?.exportAll?.()||window.OrbitalCloud?.getDecks?.()||[],industry:window.OrbitalCloud?.getIndustry?.()||[],formDraft,version:3,exported:new Date().toISOString()};}
 document.querySelector('#cloud-draft').onclick=()=>download('orbital-foundry-draft.json',currentExport());
 async function logout(){if(pending){status('Wait for saves to finish before signing out.');return;}if((dirty||failed)&&!confirm('Your draft may be unsaved. Export it before signing out. Sign out now?'))return;const {error}=await client.auth.signOut();if(error){status(error.message);return;}localStorage.removeItem(LIB);localStorage.removeItem(DES);location.reload();}
 document.querySelector('#cloud-logout').onclick=logout;document.querySelector('#cloud-reset').onclick=logout;
 document.querySelector('#cloud-login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;msg('Sending sign-in link…');try{const {error}=await client.auth.signInWithOtp({email:document.querySelector('#cloud-email').value.trim(),options:{emailRedirectTo:new URL('overview.html',location.href).href}});if(error)throw error;msg('Check your email and open the sign-in link. Only approved team accounts can access project data.');}catch(e){msg(e.message);}finally{b.disabled=false;}};

 document.querySelector('#cloud-password-login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;msg('Signing in…');try{const {error}=await client.auth.signInWithPassword({email:document.querySelector('#password-email').value.trim(),password:document.querySelector('#password-value').value});if(error)throw error;location.reload();}catch(err){msg(err.message);}finally{document.querySelector('#password-value').value='';button.disabled=false;}};
 function snapshot(){const papers=[],notes={};for(const r of rows.values()){if(r.deleted)continue;if(r.kind==='paper')papers.push(r.data);if(r.kind==='note')notes[r.id]=r.data.text||'';}return {research:{papers,notes,dataset:'blank-team-v1'},design:rows.get('project/workspace')?.data||newDesign()};}
 function cache(s){localStorage.setItem(LIB,JSON.stringify(s.research));localStorage.setItem(DES,JSON.stringify(s.design));}
 async function fetchRows(){const all=[];for(let offset=0;;offset+=500){const {data,error}=await client.from('of_entities').select('*').order('kind').order('id').range(offset,offset+499);if(error)throw error;all.push(...data);if(data.length<500)break;}return new Map(all.map(r=>[key(r.kind,r.id),r]));}
 function apply(){const s=snapshot();cache(s);optimistic=new Map([...rows].filter(([,r])=>!r.deleted).map(([k,r])=>[k,clone(r.data)]));if(ready)window.dispatchEvent(new CustomEvent('orbital-cloud-update',{detail:s}));}
 function busy(){return pending||dirty||failed||pointerDown||(ready&&!document.body.dataset.page&&view==='import')||!!document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'');}
 async function refresh(force=false){if(refreshing||pending)return;if(!force&&busy()){refreshNeeded=true;status('Team changes available — finish your edit, then Load latest.');return;}refreshing=true;try{const fresh=await fetchRows();if(!force&&busy()){refreshNeeded=true;return;}const changed=force||fresh.size!==rows.size||[...fresh].some(([k,r])=>r.revision!==rows.get(k)?.revision);rows=fresh;if(force){dirty=false;failed=false;}if(changed)apply();refreshNeeded=false;status('Synced · '+role);}catch(e){status('Could not load team changes: '+e.message);}finally{refreshing=false;}}
 document.querySelector('#cloud-reload').onclick=async()=>{if(pending){status('Wait for saves to finish.');return;}if((dirty||failed)&&!confirm('Export your current draft first if needed. Replace this page’s draft with the latest shared version?'))return;document.querySelectorAll('dialog[open]').forEach(d=>d.close());await refresh(true);};
 function rememberDraft(){try{localStorage.setItem(DRAFT,JSON.stringify(currentExport()));}catch{}}
 function enqueue(kind,id,data,deleted=false){const k=key(kind,id);const next=clone(data);pending++;queue=queue.then(async()=>{if(failed)return;const prior=rows.get(k);const {data:saved,error}=await client.rpc('of_save_entity',{p_kind:kind,p_id:id,p_data:next,p_expected_revision:prior?.revision||0,p_deleted:deleted});if(error)throw error;const row=Array.isArray(saved)?saved[0]:saved;rows.set(k,row);}).catch(e=>{failed=true;rememberDraft();status((e.code==='40001'?'Another teammate changed this record. Your draft was not overwritten.':'Save failed: '+e.message)+ ' Export current draft, then Load latest before trying again.');}).finally(()=>{pending--;if(!pending&&!failed){localStorage.removeItem(DRAFT);status('All changes saved · '+role);if(refreshNeeded)setTimeout(()=>refresh(),300);}});}
 function saveGroup(kinds,entries){if(role!=='owner'&&role!=='editor'){status('Viewer access: changes cannot be saved. Load latest to return to the shared version.');failed=true;return;}if(failed){status('Saving is paused. Export your draft, then Load latest.');return;}dirty=false;const target=new Map(entries.map(r=>[key(r.kind,r.id),r]));for(const [k,r] of target){if(!same(optimistic.get(k),r.data)){optimistic.set(k,clone(r.data));enqueue(r.kind,r.id,r.data);}}for(const [k,data] of [...optimistic]){const kind=k.slice(0,k.indexOf('/'));if(kinds.includes(kind)&&!target.has(k)){optimistic.delete(k);enqueue(kind,k.slice(kind.length+1),data,true);}}if(pending){status('Saving '+pending+' change(s)…');setTimeout(()=>{if(pending||failed)rememberDraft();},0);}}
 window.OrbitalCloud={saveResearch:s=>saveGroup(['paper','note'],[...s.papers.map(p=>({kind:'paper',id:String(p.id),data:p})),...Object.entries(s.notes||{}).map(([id,text])=>({kind:'note',id,data:{text}}))]),saveDesign:d=>saveGroup(['project'],[{kind:'project',id:'workspace',data:d}])};

 window.OrbitalCloud.getDecks=()=>[...rows.values()].filter(r=>r.kind==='diagram'&&r.id.startsWith('deck-')&&!r.deleted).map(r=>clone(r.data));
 window.OrbitalCloud.saveDeck=(deck,deleted=false)=>{if(!['owner','editor'].includes(role)||failed){status('Saving unavailable. Check your role or load the latest version first.');return false;}dirty=false;optimistic.set(key('diagram',deck.id),clone(deck));enqueue('diagram',deck.id,deck,deleted);status('Saving presentation…');return true;};
 window.OrbitalCloud.getIndustry=()=>[...rows.values()].filter(r=>r.kind==='diagram'&&r.id.startsWith('industry-')).map(r=>({...clone(r.data),id:r.id,deleted:!!r.deleted}));
 window.OrbitalCloud.saveIndustry=async(record,deleted=false)=>{if(!['owner','editor'].includes(role)||failed){status('Saving unavailable. Check your role or load the latest version first.');return false;}if(!record.id.startsWith('industry-'))throw Error('Invalid industry record');dirty=false;optimistic.set(key('diagram',record.id),clone(record));enqueue('diagram',record.id,record,deleted);status('Saving industry record…');await queue;return !failed;};
 window.OrbitalCloud.discardIndustryDraft=()=>{if(document.body.dataset.page==='industry'&&!pending&&!failed)dirty=false;};
 window.OrbitalCloud.markDirty=()=>{dirty=true;};
 window.OrbitalCloud.canEdit=()=>['owner','editor'].includes(role);
 document.addEventListener('input',e=>{if(e.target.closest('#cloud-gate,#cloud-bar,#teamContent,#midas-password,#industryFilters,#industryCharts,#feedTools')||e.target.type==='search'||['search','designSearch'].includes(e.target.id))return;dirty=true;});
 document.addEventListener('pointerdown',()=>pointerDown=true);document.addEventListener('pointerup',()=>pointerDown=false);
 window.addEventListener('beforeunload',e=>{if(pending||dirty||failed){e.preventDefault();e.returnValue='';}});
 async function loadScript(src){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src+'?v=industry1';s.onload=resolve;s.onerror=()=>reject(Error('Could not load '+src));document.body.append(s);});}
 const historyDialog=document.createElement('dialog');historyDialog.id='cloud-history';document.body.append(historyDialog);
 document.querySelector('#cloud-history-button').onclick=async()=>{historyDialog.replaceChildren();const close=document.createElement('button');close.textContent='Close';close.onclick=()=>historyDialog.close();historyDialog.append(close);historyDialog.showModal();const h=document.createElement('h2');h.textContent='Recent changes & recoverable records';historyDialog.append(h);const {data,error}=await client.from('of_history').select('*').order('updated_at',{ascending:false}).limit(100);if(error){h.textContent=error.message;return;}for(const r of data){const a=document.createElement('article'),title=document.createElement('strong'),detail=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');title.textContent=(r.data.title||r.data.project?.title||r.id)+' · '+r.kind+' · v'+r.revision+(r.deleted?' · removed':'')+' · '+new Date(r.updated_at).toLocaleString();summary.textContent='View saved contents';pre.textContent=JSON.stringify(r.data,null,2);detail.append(summary,pre);a.append(title,detail);if(role!=='viewer'){const b=document.createElement('button');b.textContent=r.deleted?'Restore removed record':'Restore this version';b.onclick=async()=>{if(pending||dirty||failed){status('Finish saving or load latest before restoring history.');return;}if(!confirm('Restore this saved version for the whole team?'))return;b.disabled=true;try{const {data:latest,error:readError}=await client.from('of_entities').select('revision').eq('kind',r.kind).eq('id',r.id).single();if(readError)throw readError;const {error:saveError}=await client.rpc('of_save_entity',{p_kind:r.kind,p_id:r.id,p_data:r.data,p_expected_revision:latest.revision,p_deleted:false});if(saveError)throw saveError;historyDialog.close();await refresh(true);}catch(e){status('Restore failed: '+e.message);}finally{b.disabled=false;}};a.append(b);}historyDialog.append(a);}if(!data.length){const p=document.createElement('p');p.textContent='No saved changes yet.';historyDialog.append(p);}};
 try{
  const {data:{session},error}=await client.auth.getSession();if(error)throw error;
  if(!session){msg('Enter your team email to get started.');return;}
  document.querySelector('#cloud-reset').hidden=false;document.querySelector('#cloud-login').hidden=true;document.querySelector('#password-option').hidden=true;document.querySelector('#register-option').hidden=true;
  const result=await client.rpc('of_my_role');if(result.error)throw result.error;role=result.data;
  if(!role){await MidasAccounts.waiting(client,gate,msg,session.user);return;}
  window.OrbitalCloud.role=()=>role;window.OrbitalCloud.teamClient=()=>client;
  MidasAccounts.passwordSettings(client,bar,session.user.email);
  if(role==='owner'){const link=document.createElement('a');link.href='team.html';link.textContent='Team management';document.querySelector('.page-links')?.append(link);}
  rows=await fetchRows();apply();
  const research=!document.body.dataset.page,presentation=document.body.dataset.page==='presentations',teamPage=document.body.dataset.page==='team',industryPage=document.body.dataset.page==='industry';
  for(const src of research?['references.js','markdown.js','app.js','research-enhancements.js','literature-tools.js']:presentation?['presentations.js']:teamPage?['team.js']:industryPage?['industry.js']:['graph-editor.js','design-pages.js'])await loadScript(src);
  window.addEventListener('orbital-cloud-update',e=>{if(research){state=e.detail.research;render();}else if(presentation){window.MidasPresentations.refresh();}else if(teamPage){}else if(industryPage){window.MidasIndustry?.refresh();}else{design=e.detail.design;designUndo=[];renderPage();}});
  ready=true;gate.hidden=true;main.inert=false;aside.inert=false;status('Connected · '+role+' · '+session.user.email);
  if(localStorage.getItem(DRAFT)){status('An earlier unsaved draft is available. Download it before making new changes.');const b=document.createElement('button');b.textContent='Download earlier draft';b.onclick=()=>download('orbital-foundry-recovered-draft.json',JSON.parse(localStorage.getItem(DRAFT)));bar.append(b);}
  client.channel('orbital-foundry-team').on('postgres_changes',{event:'*',schema:'public',table:'of_entities'},()=>{refreshNeeded=true;setTimeout(()=>refresh(),500);}).subscribe(s=>{if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')status('Live connection interrupted. Saved data remains on the server; use Load latest.');});
  setInterval(async()=>{const result=await client.rpc('of_my_role');if(result.error){status('Unable to recheck access. Retry when connected.');return;}if(result.data!==role){if(pending||dirty||failed)rememberDraft();localStorage.removeItem(LIB);localStorage.removeItem(DES);location.reload();return;}if(!busy()&&!teamPage)refresh();},30000);
  client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){main.inert=true;aside.inert=true;gate.hidden=false;msg('Signed out. Refresh to sign in again.');}});
 }catch(e){msg('Could not open the shared workspace: '+e.message+'\nRefresh to try again.');}
})();
