'use strict';
const gEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
class GraphEditor{
constructor(host,graph,options={}){this.host=host;this.graph=graph;this.options=options;this.scale=.85;this.history=[];this.selected=null;this.pending=null;this.w=options.blocks?265:220;this.h=options.blocks?148:108;this.render();requestAnimationFrame(()=>this.fit())}
checkpoint(){this.history.push(JSON.stringify(this.graph));if(this.history.length>30)this.history.shift()}
changed(){this.options.onChange?.(this.graph);this.render();this.message('Saved in this browser')}
message(t){const el=this.host.querySelector('.graph-message');if(el)el.textContent=t}
undo(){if(!this.history.length)return;const old=JSON.parse(this.history.pop());this.graph.nodes=old.nodes;this.graph.edges=old.edges;this.selected=null;this.changed()}
size(){return {width:Math.max(1200,...this.graph.nodes.map(n=>n.x+this.w+100)),height:Math.max(750,...this.graph.nodes.map(n=>n.y+this.h+100))}}
fit(){const v=this.host.querySelector('.graph-viewport');if(!v)return;const max=Math.max(1,...this.graph.nodes.map(n=>n.x+this.w+80));this.scale=Math.min(1,Math.max(.3,(v.clientWidth-20)/max));this.applyScale();v.scrollTo(0,0)}
applyScale(){const size=this.size(),world=this.host.querySelector('.graph-world'),space=this.host.querySelector('.graph-space');world.style.transform=`scale(${this.scale})`;space.style.width=size.width*this.scale+'px';space.style.height=size.height*this.scale+'px';this.host.querySelector('.zoom-value').textContent=Math.round(this.scale*100)+'%'}
point(e){const r=this.host.querySelector('.graph-world').getBoundingClientRect();return {x:(e.clientX-r.left)/this.scale,y:(e.clientY-r.top)/this.scale}}
path(a,b){const x1=a.x+this.w,y1=a.y+this.h/2,x2=b.x,y2=b.y+this.h/2;const bend=Math.max(65,Math.abs(x2-x1)*.45);return `M${x1} ${y1} C${x1+bend} ${y1},${x2-bend} ${y2},${x2} ${y2}`}
edges(){const svg=this.host.querySelector('.graph-lines');if(!svg)return;const id=this.options.id||'g';svg.innerHTML=`<defs><marker id="arrow-${id}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 Z" fill="#79b5be"/></marker></defs>`+this.graph.edges.map(e=>{const a=this.graph.nodes.find(n=>n.id===e.from),b=this.graph.nodes.find(n=>n.id===e.to);if(!a||!b)return '';const d=this.path(a,b),sel=this.selected?.type==='edge'&&this.selected.id===e.id;return `<g><path d="${d}" class="edge-hit" data-edge="${gEsc(e.id)}"/><path d="${d}" class="graph-edge ${sel?'selected':''}" marker-end="url(#arrow-${id})"/><text x="${(a.x+this.w+b.x)/2}" y="${(a.y+b.y+this.h)/2-12}" class="edge-label">${gEsc(e.label||'')}</text>${sel?`<circle cx="${b.x}" cy="${b.y+this.h/2}" r="11" class="rewire" data-rewire="${gEsc(e.id)}"><title>Drag to reconnect target</title></circle>`:''}</g>`}).join('')+(this.pending?`<path id="pending-line" d="" class="pending-edge"/>`:'')}
render(){const scroll=this.host.querySelector('.graph-viewport'),sx=scroll?.scrollLeft||0,sy=scroll?.scrollTop||0;const size=this.size();this.host.innerHTML=`<div class="graph-toolbar"><div><button type="button" data-command="add">＋ Add ${this.options.blocks?'block':'bubble'}</button><button type="button" data-command="layout">Arrange</button><button type="button" data-command="undo" ${this.history.length?'':'disabled'}>Undo</button></div><div><button type="button" data-command="out" aria-label="Zoom out">−</button><span class="zoom-value"></span><button type="button" data-command="in" aria-label="Zoom in">＋</button><button type="button" data-command="fit">Fit</button><button type="button" data-command="svg">Export SVG</button></div></div><div class="editor-split"><div><div class="graph-viewport" tabindex="0" aria-label="Interactive graph canvas"><div class="graph-space"><div class="graph-world" style="width:${size.width}px;height:${size.height}px"><svg class="graph-lines" width="${size.width}" height="${size.height}" aria-label="Graph connections"></svg>${this.graph.nodes.map(n=>`<article class="gnode ${this.options.blocks?'block-node':'bubble-node'} ${this.selected?.id===n.id?'chosen':''}" data-gnode="${gEsc(n.id)}" style="left:${n.x}px;top:${n.y}px;width:${this.w}px;height:${this.h}px;--node-color:${gEsc(/^#[0-9a-f]{6}$/i.test(n.color)?n.color:'#6be1cb')}"><button class="port in-port" aria-label="Connect to ${gEsc(n.title)}" data-port="in" data-id="${gEsc(n.id)}"></button><button class="node-grip" data-grip="${gEsc(n.id)}" aria-label="Move or edit ${gEsc(n.title)}"><span class="grip-dots">⠿</span><strong>${gEsc(n.title)}</strong><small>${gEsc(n.description||'Select to add a description')}</small></button><button class="port out-port" aria-label="Connect from ${gEsc(n.title)}" data-port="out" data-id="${gEsc(n.id)}"></button></article>`).join('')}</div></div></div><div class="canvas-help">Drag a bubble to move it. Drag its right-hand port to another bubble to connect. Select an arrow, then drag its round endpoint to reconnect. Use the inspector for keyboard editing.</div><div class="graph-message" role="status"></div></div><section class="graph-inspector" aria-label="Graph inspector"></section></div>`;this.applyScale();this.edges();const v=this.host.querySelector('.graph-viewport');v.scrollLeft=sx;v.scrollTop=sy;this.bind();this.inspector()}
bind(){this.host.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{const c=b.dataset.command;if(c==='add')this.add();if(c==='undo')this.undo();if(c==='fit')this.fit();if(c==='in'||c==='out'){this.scale=Math.max(.3,Math.min(1.8,this.scale+(c==='in'?.1:-.1)));this.applyScale()}if(c==='layout'){this.checkpoint();this.graph.nodes.forEach((n,i)=>{n.x=70+(i%3)*(this.w+110);n.y=70+Math.floor(i/3)*(this.h+120)});this.changed();this.fit()}if(c==='svg')this.exportSVG()});
const v=this.host.querySelector('.graph-viewport');let drag=null;
v.onpointerdown=e=>{const port=e.target.closest('[data-port]'),rewire=e.target.closest('[data-rewire]'),grip=e.target.closest('[data-grip]'),edge=e.target.closest('[data-edge]');if(port){e.preventDefault();if(port.dataset.port==='out'){this.pending={from:port.dataset.id};this.edges();drag={type:'connect'};this.message('Release over another bubble to create a connection.')}return}if(rewire){e.preventDefault();const item=this.graph.edges.find(x=>x.id===rewire.dataset.rewire);this.pending={from:item.from,edge:item.id};this.edges();drag={type:'connect'};return}if(grip){e.preventDefault();const n=this.graph.nodes.find(n=>n.id===grip.dataset.grip);this.selected={type:'node',id:n.id};this.inspector();this.host.querySelectorAll('.gnode').forEach(el=>el.classList.toggle('chosen',el.dataset.gnode===n.id));this.edges();const p=this.point(e);drag={type:'node',n,x:p.x,y:p.y,nx:n.x,ny:n.y,moved:false};v.setPointerCapture(e.pointerId);return}if(edge){this.selected={type:'edge',id:edge.dataset.edge};this.edges();this.inspector();return}drag={type:'pan',x:e.clientX,y:e.clientY,sx:v.scrollLeft,sy:v.scrollTop};v.setPointerCapture(e.pointerId)};
v.onpointermove=e=>{if(!drag)return;if(drag.type==='node'){const p=this.point(e);if(!drag.moved&&Math.hypot(p.x-drag.x,p.y-drag.y)>3){this.checkpoint();drag.moved=true}if(drag.moved){drag.n.x=Math.max(15,Math.min(4000,drag.nx+p.x-drag.x));drag.n.y=Math.max(15,Math.min(3000,drag.ny+p.y-drag.y));const el=[...this.host.querySelectorAll('.gnode')].find(el=>el.dataset.gnode===drag.n.id);el.style.left=drag.n.x+'px';el.style.top=drag.n.y+'px';this.edges()}}else if(drag.type==='pan'){v.scrollLeft=drag.sx+drag.x-e.clientX;v.scrollTop=drag.sy+drag.y-e.clientY}else{const a=this.graph.nodes.find(n=>n.id===this.pending.from),p=this.point(e);this.host.querySelector('#pending-line')?.setAttribute('d',`M${a.x+this.w} ${a.y+this.h/2} L${p.x} ${p.y}`)}};
v.onpointerup=e=>{if(drag?.type==='connect'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-gnode]');if(target)this.connect(this.pending.from,target.dataset.gnode,this.pending.edge);else this.message('Connection cancelled. Drop on another bubble.');this.pending=null;this.edges()}else if(drag?.type==='node'&&drag.moved){this.options.onChange?.(this.graph);this.render()}drag=null};v.onpointercancel=()=>{drag=null;this.pending=null;this.edges()};
this.host.querySelectorAll('[data-grip]').forEach(b=>{b.onclick=()=>{this.selected={type:'node',id:b.dataset.grip};this.inspector();this.edges()};b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();this.checkpoint();const n=this.graph.nodes.find(n=>n.id===b.dataset.grip);n.x=Math.max(15,n.x+(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0));n.y=Math.max(15,n.y+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0));this.changed();[...this.host.querySelectorAll('[data-grip]')].find(x=>x.dataset.grip===n.id)?.focus()}}});
this.host.querySelectorAll('[data-port]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.port==='out'){this.pending={from:b.dataset.id};this.edges();this.message('Now select another bubble’s left port, or use the inspector.')}else if(this.pending){this.connect(this.pending.from,b.dataset.id,this.pending.edge);this.pending=null;this.edges()}});v.onkeydown=e=>{if(e.key==='Escape'){this.pending=null;this.edges();this.message('Connection cancelled')}};
}
connect(from,to,replace){if(from===to){this.message('Choose a different destination bubble.');return}if(this.graph.edges.some(e=>e.from===from&&e.to===to&&e.id!==replace)){this.message('That connection already exists.');return}this.checkpoint();if(replace){const e=this.graph.edges.find(e=>e.id===replace);e.to=to;this.selected={type:'edge',id:e.id}}else{const e={id:crypto.randomUUID(),from,to,label:'',type:'flow'};this.graph.edges.push(e);this.selected={type:'edge',id:e.id}}this.pending=null;this.changed()}
add(){this.checkpoint();const id=crypto.randomUUID(),i=this.graph.nodes.length;this.graph.nodes.push({id,title:this.options.blocks?'New block':'New function',description:'',stage:'',keywords:[],x:80+(i%3)*(this.w+90),y:80+Math.floor(i/3)*(this.h+110),color:'#6be1cb'});this.selected={type:'node',id};this.changed();const n=this.graph.nodes.at(-1);this.host.querySelector('.graph-viewport').scrollTo(Math.max(0,n.x*this.scale-100),Math.max(0,n.y*this.scale-100))}
inspector(){const host=this.host.querySelector('.graph-inspector'),selected=this.selected;host.innerHTML='<p class="eyebrow">GRAPH INSPECTOR</p>';if(!selected){host.innerHTML+='<h3>Build the connections.</h3><p>Select a bubble to edit its title and purpose. Select an arrow to edit or remove a connection.</p><p class="note">Keyboard: tab to a bubble and press Enter to edit. Arrow keys move the focused bubble. Connections can also be added using the form below.</p>'+this.connectionForm();this.bindConnectionForm();return}
if(selected.type==='node'){const n=this.graph.nodes.find(n=>n.id===selected.id);if(!n){this.selected=null;this.inspector();return}host.innerHTML+=`<h3>Edit ${this.options.blocks?'block':'bubble'}</h3><form class="node-form"><label>Title<input name="title" required maxlength="100" value="${gEsc(n.title)}"></label><label>Description<textarea name="description">${gEsc(n.description)}</textarea></label><label>Research stage<select name="stage"><option value="">Cross-cutting / unassigned</option>${typeof nodes!=='undefined'?nodes.map(s=>`<option value="${s.id}" ${n.stage===s.id?'selected':''}>${gEsc(s.title)}</option>`).join(''):''}</select></label><label>Colour<input type="color" name="color" value="${/^#[0-9a-f]{6}$/i.test(n.color)?n.color:'#6be1cb'}"></label><button class="primary">Save bubble</button><button type="button" class="remove-node danger">Remove bubble</button></form>${this.options.openSubsystem&&this.options.openSubsystem(n.id)?`<a class="button-link" href="subsystems.html?system=${encodeURIComponent(n.id)}">Open subsystem tree</a>`:''}${n.stage?`<a class="button-link" href="index.html#tree">Explore linked research</a>`:''}${this.connectionForm(n.id)}`;host.querySelector('.node-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!f.get('title').trim())return;this.checkpoint();Object.assign(n,{title:f.get('title').trim(),description:f.get('description'),stage:f.get('stage'),color:f.get('color')});this.changed()};host.querySelector('.remove-node').onclick=()=>{this.checkpoint();this.graph.nodes=this.graph.nodes.filter(x=>x.id!==n.id);this.graph.edges=this.graph.edges.filter(e=>e.from!==n.id&&e.to!==n.id);this.selected=null;this.changed();this.message('Bubble removed. Use Undo to restore it.')};this.bindConnectionForm()}
else{const edge=this.graph.edges.find(e=>e.id===selected.id);if(!edge){this.selected=null;this.inspector();return}host.innerHTML+=`<h3>Edit connection</h3><p class="note">Drag the round target endpoint onto another bubble to reconnect.</p><form class="edge-form"><label>From<select name="from">${this.optionsHTML(edge.from)}</select></label><label>To<select name="to">${this.optionsHTML(edge.to)}</select></label><label>Connection label<input name="label" value="${gEsc(edge.label)}" maxlength="70"></label><button class="primary">Save connection</button><button type="button" class="remove-edge danger">Remove connection</button></form>`;host.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),from=f.get('from'),to=f.get('to');if(from===to||this.graph.edges.some(x=>x.id!==edge.id&&x.from===from&&x.to===to)){this.message('Choose two different bubbles without an existing connection.');return}this.checkpoint();Object.assign(edge,{from,to,label:f.get('label')});this.changed()};host.querySelector('.remove-edge').onclick=()=>{this.checkpoint();this.graph.edges=this.graph.edges.filter(e=>e.id!==edge.id);this.selected=null;this.changed()}}
}
optionsHTML(selected){return this.graph.nodes.map(n=>`<option value="${gEsc(n.id)}" ${n.id===selected?'selected':''}>${gEsc(n.title)}</option>`).join('')}
connectionForm(from){return `<form class="connect-form"><h3>Add a connection</h3><label>From<select name="from">${this.optionsHTML(from)}</select></label><label>To<select name="to">${this.optionsHTML('')}</select></label><label>Label<input name="label" placeholder="Material, power, data…" maxlength="70"></label><button ${this.graph.nodes.length<2?'disabled':''}>Connect bubbles</button></form>`}
bindConnectionForm(){const form=this.host.querySelector('.connect-form');if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),from=f.get('from'),to=f.get('to');if(from===to||this.graph.edges.some(e=>e.from===from&&e.to===to)){this.message('Choose two different bubbles without an existing connection.');return}this.checkpoint();this.graph.edges.push({id:crypto.randomUUID(),from,to,label:f.get('label')});this.changed()}}
exportSVG(){const size=this.size();const split=t=>String(t||'').match(/.{1,28}(?:\s|$)|.{1,28}/g)||[];const content=`<svg xmlns="http://www.w3.org/2000/svg" width="${size.width}" height="${size.height}" viewBox="0 0 ${size.width} ${size.height}"><rect width="100%" height="100%" fill="#0c1823"/><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10 Z" fill="#79b5be"/></marker></defs>${this.graph.edges.map(e=>{const a=this.graph.nodes.find(n=>n.id===e.from),b=this.graph.nodes.find(n=>n.id===e.to);return a&&b?`<path d="${this.path(a,b)}" fill="none" stroke="#79b5be" stroke-width="2" marker-end="url(#a)"/><text x="${(a.x+this.w+b.x)/2}" y="${(a.y+b.y+this.h)/2-12}" fill="#bacbd6" font-family="Arial" font-size="12">${gEsc(e.label)}</text>`:''}).join('')}${this.graph.nodes.map(n=>`<rect x="${n.x}" y="${n.y}" width="${this.w}" height="${this.h}" rx="${this.options.blocks?12:35}" fill="#17303c" stroke="${gEsc(n.color)}" stroke-width="2"/><text x="${n.x+18}" y="${n.y+30}" fill="#edf3f8" font-family="Arial" font-size="15">${split(n.title).slice(0,2).map((line,i)=>`<tspan x="${n.x+18}" dy="${i?19:0}">${gEsc(line)}</tspan>`).join('')}</text><text x="${n.x+18}" y="${n.y+76}" fill="#bdcbd4" font-family="Arial" font-size="12">${gEsc(n.description.slice(0,34))}${n.description.length>34?'…':''}</text>`).join('')}</svg>`;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type:'image/svg+xml'}));a.href=url;a.download=this.options.blocks?'project-block-diagram.svg':'subsystem-tree.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
}
