'use strict';
(async function(){
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safe=u=>{try{const p=new URL(u);return ['http:','https:'].includes(p.protocol)?p.href:'';}catch{return '';}};
 const dialog=$('#industryDialog'),body=$('#industryDialogBody');let seed,companies=[],records=[],sector=null,editDirty=false,feed={items:[],sources:[]};
 const editable=()=>OrbitalCloud.canEdit(),sectorBy=id=>seed.sectors.find(s=>s.id===id),uid=()=>crypto.randomUUID();
 function notice(text){let e=$('#industryMessage');if(!e){e=document.createElement('p');e.id='industryMessage';e.setAttribute('role','status');$('#industryFilters').after(e);}e.textContent=text;}
 function merge(){records=OrbitalCloud.getIndustry();const map=new Map(seed.companies.map(c=>[c.id,structuredClone(c)]));records.filter(r=>r.id.startsWith('industry-company-')).forEach(r=>r.deleted?map.delete(r.id):map.set(r.id,r));companies=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));}
 function arc(a,b,r=160,inner=105){const pt=(angle,rad)=>[200+rad*Math.cos(angle-Math.PI/2),200+rad*Math.sin(angle-Math.PI/2)];const p=pt(a,r),q=pt(b,r),x=pt(b,inner),y=pt(a,inner),large=b-a>Math.PI?1:0;return `M${p} A${r},${r} 0 ${large} 1 ${q} L${x} A${inner},${inner} 0 ${large} 0 ${y} Z`;}
 function chart(){const counts=seed.sectors.map(s=>companies.filter(c=>c.programmes.some(p=>p.sector===s.id)).length),total=counts.reduce((a,b)=>a+b,0);let angle=0;const paths=seed.sectors.map((s,i)=>{const start=angle;angle+=total?counts[i]/total*Math.PI*2:0;return counts[i]?`<path class="sector-slice ${sector===s.id?'selected':''}" style="--slice:${i};fill:${s.color}" d="${arc(start+.012,Math.max(start+.014,angle-.012))}" role="button" tabindex="0" data-sector="${s.id}" aria-label="${esc(s.title)}: ${counts[i]} company profiles" aria-pressed="${sector===s.id}"><title>${esc(s.title)} · ${counts[i]} profiles</title></path>`:'';}).join('');const reviewed=companies.filter(c=>c.verification==='reviewed').length;
 $('#industryCharts').innerHTML=`<article class="sector-chart-panel"><div class="chart-caption"><p class="eyebrow">SECTOR EXPLORER</p><h2>One ecosystem. Eight perspectives.</h2></div><div class="sector-chart-layout"><div class="donut-wrap"><svg viewBox="0 0 400 400" aria-label="Sector participation chart">${paths}</svg><div class="donut-centre" aria-live="polite"><strong id="donutNumber">${companies.length}</strong><span id="donutLabel">company / consortium profiles</span><small>Click a slice to explore</small></div></div><div class="sector-key">${seed.sectors.map((s,i)=>`<button data-sector="${s.id}" aria-pressed="${sector===s.id}" style="--sector:${s.color}"><i></i><span>${esc(s.title)}</span><strong>${counts[i]}</strong></button>`).join('')}</div></div><p class="chart-footnote">${total} sector participations · Multi-sector profiles count in each relevant slice.</p></article><article class="evidence-chart-panel"><p class="eyebrow">RESEARCH CONFIDENCE</p><h2>Evidence, kept visible.</h2><div class="evidence-donut" style="--review:${companies.length?reviewed/companies.length*100:0}%"><div><strong>${reviewed}</strong><span>team-reviewed profiles</span></div></div><button data-evidence="reviewed"><i class="green-dot"></i>Team reviewed <strong>${reviewed}</strong></button><button data-evidence="imported"><i class="amber-dot"></i>Imported / unverified <strong>${companies.length-reviewed}</strong></button><p>Review labels reflect the team’s assessment, not independent certification.</p></article>`;
 $('#industryCharts').querySelectorAll('[data-sector]').forEach(el=>{const select=()=>{sector=sector===el.dataset.sector?null:el.dataset.sector;render();$('#sectorHeading').scrollIntoView({behavior:'smooth',block:'nearest'});};el.onclick=select;el.onkeydown=e=>{if(el.tagName.toLowerCase()==='path'&&['Enter',' '].includes(e.key)){e.preventDefault();select();}};el.onmouseenter=()=>{$('#donutNumber').textContent=counts[seed.sectors.findIndex(s=>s.id===el.dataset.sector)];$('#donutLabel').textContent=sectorBy(el.dataset.sector).title;};el.onmouseleave=()=>{$('#donutNumber').textContent=companies.length;$('#donutLabel').textContent='company / consortium profiles';};});$('#industryCharts').querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{$('#verificationFilter').value=b.dataset.evidence;list();});
 }
 function list(){const query=$('#companySearch').value.toLowerCase().trim(),verification=$('#verificationFilter').value;const shown=companies.filter(c=>(!sector||c.programmes.some(p=>p.sector===sector))&&(verification==='all'||c.verification===verification)&&(!query||JSON.stringify([c.name,c.notes,c.programmes]).toLowerCase().includes(query)));$('#sectorHeading').textContent=sector?sectorBy(sector)?.title:'All sectors';$('#companyCount').textContent=`${shown.length} of ${companies.length} profiles · click a card to inspect or edit`;
 $('#companyCards').innerHTML=shown.map(c=>{const sectors=[...new Set(c.programmes.map(p=>p.sector))],p=c.programmes.find(p=>p.sector===sector)||c.programmes[0];return `<button class="company-card" data-company="${esc(c.id)}" style="--accent:${sectorBy(p?.sector)?.color||'#62debf'}"><div class="card-top"><span>${c.verification==='reviewed'?'TEAM REVIEWED':'IMPORTED / UNVERIFIED'}</span><span>↗</span></div><h3>${esc(c.name)}</h3><p>${esc(p?.description||'Add a description.')}</p><div class="sector-pills">${sectors.map(id=>`<span>${esc(sectorBy(id)?.title||'Uncategorised')}</span>`).join('')}</div><small>${c.programmes.length} sector ${c.programmes.length===1?'entry':'entries'}${c.checkedAt?' · checked '+esc(c.checkedAt):''}</small></button>`;}).join('')||'<div class="empty">No profiles match. Try another sector or search.</div>';$('#companyCards').querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>showCompany(b.dataset.company));
 }
 function render(){merge();chart();list();renderNews();}
 function programmeFields(p,i){return `<fieldset><legend>Sector entry ${i+1}</legend><label>Sector<select name="sector-${i}">${seed.sectors.map(s=>`<option value="${s.id}" ${s.id===p.sector?'selected':''}>${esc(s.title)}</option>`).join('')}</select></label><label>Organisation / regional entity<input name="organisation-${i}" value="${esc(p.organisation||'')}"></label><label>Technology and description<textarea name="description-${i}" rows="3">${esc(p.description||'')}</textarea></label><label>Status and milestones (distinguish planned from completed)<textarea name="status-${i}" rows="4">${esc(p.status||'')}</textarea></label><label><input type="checkbox" name="remove-${i}"> Remove this sector entry on save</label></fieldset>`;}
 function showCompany(id){const c=companies.find(c=>c.id===id);if(!c)return;body.innerHTML=`<p class="eyebrow">COMPANY INTELLIGENCE</p><h2>${esc(c.name)}</h2><p class="verification-banner">${c.verification==='reviewed'?'Team reviewed · '+esc(c.checkedAt):'Imported team assessment — not independently verified'}</p>${c.programmes.map(p=>`<section class="programme-detail"><span class="tag">${esc(sectorBy(p.sector)?.title)}</span><h3>${esc(p.organisation)}</h3><p>${esc(p.description)}</p><h4>Reported status</h4><p>${esc(p.status)}</p></section>`).join('')}<h3>MIDAS relevance / team notes</h3><p class="preserve-lines">${esc(c.notes||'No team notes yet.')}</p>${safe(c.sourceUrl)?`<a href="${esc(safe(c.sourceUrl))}" target="_blank" rel="noopener">Open verification source ↗</a>`:''}<h3>Reviewed news references</h3>${(c.evidence||[]).map(n=>`<p><a href="${esc(safe(n.url))}" target="_blank" rel="noopener">${esc(n.title)}</a><br>${esc(n.note)}<small> · reviewed ${esc(n.reviewedAt)}</small></p>`).join('')||'<p>No reviewed news attached.</p>'}${editable()?'<div class="industry-actions"><button id="editCompany" class="primary">Edit shared profile</button><button id="removeCompany">Remove profile</button></div>':'<p>Viewer access · ask an editor to make changes.</p>'}`;if(editable()){$('#editCompany').onclick=()=>editCompany(c);$('#removeCompany').onclick=async()=>{if(!confirm('Remove '+c.name+' from the shared industry page? The record remains recoverable through History & restore.'))return;const ok=await OrbitalCloud.saveIndustry({...c,deleted:true},true);if(ok){dialog.close();render();}else notice('Removal could not be saved. Load latest before retrying.');};}if(!dialog.open)dialog.showModal();}
 function editCompany(existing){if(!editable())return;const c=structuredClone(existing||{id:'industry-company-'+uid(),name:'',programmes:[{sector:sector||seed.sectors[0].id,organisation:'',description:'',status:''}],notes:'',verification:'imported',sourceUrl:'',checkedAt:'',evidence:[]});
 function draw(){body.innerHTML=`<h2>${existing?'Edit':'Add'} company profile</h2><form id="companyForm"><label>Company / consortium name<input name="name" required maxlength="180" value="${esc(c.name)}"></label>${c.programmes.map(programmeFields).join('')}<button type="button" id="addProgramme">＋ Another sector entry</button><label>MIDAS relevance / team notes<textarea name="notes" rows="4">${esc(c.notes)}</textarea></label><label>Evidence status<select name="verification"><option value="imported" ${c.verification!=='reviewed'?'selected':''}>Imported / unverified</option><option value="reviewed" ${c.verification==='reviewed'?'selected':''}>Team reviewed</option></select></label><label>Verification source URL<input name="sourceUrl" type="url" value="${esc(c.sourceUrl||'')}" placeholder="https://…"></label><label>Last checked date<input name="checkedAt" type="date" value="${esc(c.checkedAt||'')}"></label><p id="editFeedback" role="status"></p><button class="primary" type="submit">Save for everyone</button></form>`;
 const collect=()=>{const f=new FormData($('#companyForm'));return {...c,name:f.get('name').trim(),notes:f.get('notes'),verification:f.get('verification'),sourceUrl:f.get('sourceUrl').trim(),checkedAt:f.get('checkedAt'),deleted:false,programmes:c.programmes.map((p,i)=>({...p,sector:f.get('sector-'+i),organisation:f.get('organisation-'+i),description:f.get('description-'+i),status:f.get('status-'+i)})).filter((p,i)=>!f.has('remove-'+i))};};
 $('#addProgramme').onclick=()=>{Object.assign(c,collect());c.programmes.push({sector:seed.sectors[0].id,organisation:c.name,description:'',status:''});draw();};
 $('#companyForm').onsubmit=async e=>{e.preventDefault();const value=collect();if(!value.programmes.length){$('#editFeedback').textContent='Keep at least one sector entry.';return;}if(value.verification==='reviewed'&&(!safe(value.sourceUrl)||!value.checkedAt)){$('#editFeedback').textContent='A team-reviewed profile needs a source URL and checked date.';return;}e.submitter.disabled=true;const ok=await OrbitalCloud.saveIndustry(value);if(ok){dialog.close();render();notice('Shared profile saved.');}else{$('#editFeedback').textContent='Save failed. Export your draft or use Load latest; your form is still here.';e.submitter.disabled=false;}};
 }draw();if(!dialog.open)dialog.showModal();}
 function reviewNews(n){if(!editable())return;body.innerHTML=`<h2>Review an announcement</h2><p><a href="${esc(safe(n.url))}" target="_blank" rel="noopener">${esc(n.title)} ↗</a></p><p>Read the source, choose a company and record what it supports. This attaches evidence; mission status is changed only when you edit that profile.</p><form id="reviewForm"><label>Company<select name="company">${companies.map(c=>`<option value="${c.id}" ${(n.companyIds||[]).includes(c.id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Your review / relevance<textarea name="note" rows="4" required></textarea></label><p id="reviewFeedback" role="status"></p><button class="primary">Save reviewed reference</button></form>`;dialog.showModal();$('#reviewForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const f=new FormData(e.target),c=structuredClone(companies.find(c=>c.id===f.get('company')));c.evidence=[...(c.evidence||[]).filter(x=>x.id!==n.id),{id:n.id,title:n.title,url:n.url,published:n.published,note:f.get('note'),reviewedAt:new Date().toISOString().slice(0,10)}];if(await OrbitalCloud.saveIndustry(c)&&await OrbitalCloud.saveIndustry({id:'industry-review-'+n.id,status:'reviewed',companyId:c.id,note:f.get('note')})){dialog.close();render();}else{$('#reviewFeedback').textContent='Save failed. Load latest before retrying.';e.submitter.disabled=false;}};}
 function renderNews(){const reviews=new Map(records.filter(r=>r.id.startsWith('industry-review-')&&!r.deleted).map(r=>[r.id,r]));const shown=(feed.items||[]).filter(n=>$('#feedFilter').value==='all'||!reviews.has('industry-review-'+n.id));$('#newsCards').innerHTML=shown.slice(0,100).map(n=>{const review=reviews.get('industry-review-'+n.id);return `<article class="news-card"><small>${esc(n.source)} · ${esc(n.published||'Publication date unavailable')}</small><h3><a href="${esc(safe(n.url))}" target="_blank" rel="noopener">${esc(n.title)} ↗</a></h3><p>${esc(n.matchReason||'Potential ISAM relevance — review required')}</p>${review?`<span class="tag">${esc(review.status)}</span>`:editable()?`<div class="industry-actions"><button data-review="${n.id}">Review & link</button><button data-dismiss="${n.id}">Dismiss</button></div>`:'<p>Awaiting editor review</p>'}</article>`;}).join('')||'<p class="empty">No captured updates awaiting review. This does not mean there have been no industry developments.</p>';
 $('#newsCards').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewNews(feed.items.find(n=>n.id===b.dataset.review)));$('#newsCards').querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=async()=>{b.disabled=true;if(await OrbitalCloud.saveIndustry({id:'industry-review-'+b.dataset.dismiss,status:'dismissed'}))render();else b.disabled=false;});}
 async function loadFeed(){try{let r;try{r=await fetch('https://raw.githubusercontent.com/AndreasPoimen/3rd-Year-Project/main/industry-data/news.json',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();}catch{r=await fetch('./industry-data/news.json');}if(!r.ok)throw Error();feed=await r.json();$('#feedStatus').textContent=`Last check: ${feed.checkedAt?new Date(feed.checkedAt).toLocaleString():'not yet run'} · ${(feed.sources||[]).map(s=>s.name+': '+(s.ok?'checked':s.error||'unavailable')).join(' · ')}. ${feed.items.length} captured headlines. Scheduled daily; reload to retrieve newer results.`;renderNews();}catch{$('#feedStatus').textContent='News feed unavailable. Shared profiles are still usable.';}}
 body.addEventListener('input',()=>editDirty=true);function closePanel(){if(editDirty&&!confirm('Discard the unsaved changes in this panel?'))return;OrbitalCloud.discardIndustryDraft();dialog.close();}dialog.addEventListener('cancel',e=>{e.preventDefault();closePanel();});dialog.addEventListener('close',()=>editDirty=false);$('#closeIndustryDialog').onclick=closePanel;$('#companySearch').oninput=list;$('#verificationFilter').onchange=list;$('#resetIndustry').onclick=()=>{sector=null;$('#companySearch').value='';$('#verificationFilter').value='all';render();};$('#feedFilter').onchange=renderNews;$('#reloadFeed').onclick=loadFeed;$('#addCompany').onclick=()=>editCompany();$('#exportIndustry').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({sectors:seed.sectors,companies,reviews:records.filter(r=>r.id.startsWith('industry-review-')),exportedAt:new Date().toISOString()},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='MIDAS-industry-landscape.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 setInterval(()=>{if(!document.hidden&&!dialog.open)loadFeed();},300000);
 window.MidasIndustry={refresh:()=>{if(seed)render();}};
 try{const response=await fetch('./industry-data/seed.json');if(!response.ok)throw Error('Seed unavailable');seed=await response.json();$('#addCompany').disabled=!editable();render();await loadFeed();}catch(e){$('#companyCards').textContent='Industry data could not load: '+e.message;}
})();
