'use strict';
// Enhances the existing import and paper detail views without changing their data model.
const basePaperView=openPaper,baseImportView=renderImport;
async function copyCitation(text,button){try{await navigator.clipboard.writeText(text);const label=button.textContent;button.textContent='Copied ✓';setTimeout(()=>button.textContent=label,1800);}catch{button.textContent='Select the text below and copy manually';}}
openPaper=function(id){basePaperView(id);const p=state.papers.find(p=>p.id===id);if(!p)return;const section=document.createElement('section');section.className='detailSection reference-tools';section.innerHTML='<h3>Cite this source</h3><p class="note">Generated from this record. Check missing metadata and your required citation style before submission.</p><label>Author–date reference</label><textarea readonly id="formattedReference" aria-label="Formatted reference"></textarea><button type="button" id="copyReference">Copy reference</button><label>BibTeX for your .bib file</label><textarea readonly id="bibtexReference" aria-label="BibTeX entry"></textarea><button type="button" id="copyBibtex">Copy BibTeX</button><button type="button" id="copyCite">Copy LaTeX cite command</button><p id="citationMissing" class="note"></p>';$('#detailBody').append(section);$('#formattedReference').value=MidasReferences.reference(p);$('#bibtexReference').value=MidasReferences.bibtex(p);$('#copyReference').onclick=e=>copyCitation($('#formattedReference').value,e.currentTarget);$('#copyBibtex').onclick=e=>copyCitation($('#bibtexReference').value,e.currentTarget);$('#copyCite').onclick=e=>copyCitation('\\cite{'+MidasReferences.citeKey(p)+'}',e.currentTarget);$('#citationMissing').textContent='Missing: '+(['authors','year','title'].filter(k=>!p[k]).join(', ')||'no essential fields flagged')+'. Use Edit record to correct details.';};
renderImport=function(q){baseImportView(q);const urlField=$('#sourceURL');urlField.type='text';urlField.placeholder='Website address, DOI, or doi.org link';$('#fetchStatus').textContent='DOIs use Crossref/DataCite. Other pages work when they allow browser access. Manual entry is always available.';const box=document.createElement('details');box.className='bibliographic-fields';box.innerHTML='<summary>Bibliography details · journal, DOI, pages and more</summary>'+[['doi','DOI'],['journal','Journal'],['booktitle','Conference / book title'],['publisher','Publisher'],['volume','Volume'],['issue','Issue'],['pages','Pages']].map(([k,l])=>`<label for="bib-${k}">${l}</label><input id="bib-${k}" value="${esc(importDraft[k]||'')}">`).join('')+'<label for="bib-entryType">BibTeX entry type</label><select id="bib-entryType">'+['misc','article','inproceedings','book','techreport'].map(k=>`<option ${importDraft.entryType===k?'selected':''}>${k}</option>`).join('')+'</select>';$('#importForm').insertBefore(box,$('#importForm button[type="submit"]'));const help=document.createElement('p');help.className='note';help.textContent='For manual authors, separate people with semicolons, e.g. Smith, Jane; Jones, Alex.';$('#authors').after(help);const manual=document.createElement('button');manual.type='button';manual.textContent='Create a custom entry instead';manual.id='manualEntry';$('#fetchStatus').after(manual);manual.onclick=()=>{$('#paperTitle').focus();$('#fetchStatus').textContent='Enter a title and any details you know, then Add to literature. Your link does not need to support metadata fetching.';};const submit=$('#importForm').onsubmit;$('#importForm').onsubmit=e=>{const normalized=MidasReferences.url(urlField.value);if(urlField.value.trim()&&!normalized){e.preventDefault();toast('Use a public HTTP/HTTPS link or DOI. You can leave the link blank.');return;}urlField.value=normalized;for(const k of ['doi','journal','booktitle','publisher','volume','issue','pages','entryType'])importDraft[k]=$('#bib-'+k).value.trim();if(importDraft.authorList&&$('#authors').value!==importDraft._loadedAuthors)delete importDraft.authorList;submit(e);};};
async function metadataJSON(endpoint){const r=await fetch(endpoint,{signal:AbortSignal.timeout(10000),credentials:'omit'});if(!r.ok)throw Error('Metadata service returned '+r.status);return r.json();}
function stripMarkup(s){return new DOMParser().parseFromString(String(s||''),'text/html').body.textContent||'';}
async function lookupDOI(doi){try{const {message:m}=await metadataJSON('https://api.crossref.org/works/'+encodeURIComponent(doi));return {title:stripMarkup(m.title?.[0]),authorList:(m.author||[]).map(a=>({given:a.given||'',family:a.family||a.name||''})),year:m.published?.['date-parts']?.[0]?.[0]||'',summary:stripMarkup(m.abstract),journal:m.type==='journal-article'?m['container-title']?.[0]||'':'',booktitle:m.type==='proceedings-article'?m['container-title']?.[0]||'':'',publisher:m.publisher,volume:m.volume,issue:m.issue,pages:m.page,doi:m.DOI,entryType:m.type==='journal-article'?'article':m.type==='proceedings-article'?'inproceedings':m.type==='book'?'book':'misc',metadataSource:'Crossref'};}catch{const {data:{attributes:m}}=await metadataJSON('https://api.datacite.org/dois/'+encodeURIComponent(doi));return {title:m.titles?.[0]?.title||'',authorList:(m.creators||[]).map(a=>a.familyName?{family:a.familyName,given:a.givenName||''}:a.name),year:m.publicationYear,summary:stripMarkup(m.descriptions?.[0]?.description),publisher:typeof m.publisher==='string'?m.publisher:m.publisher?.name,doi:m.doi,entryType:'misc',metadataSource:'DataCite'};}}
fetchMetadata=async function(){const field=$('#sourceURL'),url=MidasReferences.url(field.value),button=$('#fetchMeta'),status=$('#fetchStatus');if(!url){status.textContent='Enter a website address or DOI, or choose custom entry.';return;}field.value=url;button.disabled=true;status.textContent='Looking up source details…';try{let metadata,doi=MidasReferences.doi($('#bib-doi')?.value)||MidasReferences.doi(url);if(doi)metadata=await lookupDOI(doi);else{const r=await fetch(url,{signal:AbortSignal.timeout(10000),credentials:'omit'});if(!r.ok)throw Error('Page unavailable');const type=r.headers.get('content-type')||'';if(type.includes('pdf'))throw Error('PDF metadata needs manual entry or a DOI');const doc=new DOMParser().parseFromString((await r.text()).slice(0,2000000),'text/html');const meta=n=>doc.querySelector(`meta[name="${n}"],meta[property="${n}"]`)?.content||'';doi=MidasReferences.doi(meta('citation_doi')||meta('DC.Identifier'));if(doi){try{metadata=await lookupDOI(doi);}catch{}}metadata=metadata||{title:meta('citation_title')||meta('og:title')||doc.title,authors:[...doc.querySelectorAll('meta[name="citation_author"]')].map(e=>e.content).join('; ')||meta('author'),year:(meta('citation_publication_date')||meta('article:published_time')).match(/\d{4}/)?.[0]||'',summary:meta('description')||meta('og:description'),journal:meta('citation_journal_title'),volume:meta('citation_volume'),issue:meta('citation_issue'),pages:[meta('citation_firstpage'),meta('citation_lastpage')].filter(Boolean).join('--'),doi,metadataSource:'Source page'};}
 // An in-flight request must not populate a different source or a new page.
 if(!field.isConnected||MidasReferences.url(field.value)!==url)return;
 const names=metadata.authorList?MidasReferences.authors(metadata).join('; '):metadata.authors||'';for(const [id,value] of Object.entries({paperTitle:metadata.title,authors:names,year:metadata.year,summary:metadata.summary})){if(value&&!$('#'+id).value)$('#'+id).value=value;}if(names&&$('#authors').value===names){importDraft.authorList=metadata.authorList;importDraft._loadedAuthors=names;}for(const k of ['doi','journal','booktitle','publisher','volume','issue','pages','entryType'])if(metadata[k]&&$('#bib-'+k)&&(!$('#bib-'+k).value||k==='entryType'))$('#bib-'+k).value=metadata[k];importDraft.metadataSource=metadata.metadataSource;status.textContent=metadata.metadataSource+' details loaded. Existing text was kept. Review everything before saving.';
 }catch{if(field.isConnected)status.textContent='Automatic details are unavailable for this source (access restriction, browser policy or missing metadata). Your link is kept: enter its title manually, or paste a DOI and try again. You can still save the record.';}finally{button.disabled=false;}};
const paperWithReferences=openPaper;
openPaper=function(id){paperWithReferences(id);const p=state.papers.find(p=>p.id===id);if(!p)return;const button=document.createElement('button');button.type='button';button.id='downloadPaperMarkdown';button.className='primary';button.textContent='Download Markdown (.md)';button.title='Download only this literature record';$('#detailBody h2').after(button);button.onclick=()=>{download(MidasMarkdown.filename(p),MidasMarkdown.paper(p,nodes),'text/markdown;charset=utf-8');toast('This literature record was exported as Markdown');};};
render();
