import {categories,matches,dimensionLabel} from './orbit-catalogue.js';
import {initExplorer} from './catalogue-explorer.js';
import * as THREE from './vendor/orbits/three.module.min.js';
import {OrbitControls} from './vendor/orbits/OrbitControls.js';
import {parseRow,position,orbit} from './orbit-math.js';
const $=s=>document.querySelector(s),host=$('#globe'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.01,500);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],selected=-1,visible=[],pointIndexes=[],coords,valid,worker,busy=false,lastTick=0,lastDetails=0,lastOrbit=0,paused=false,pausedAt=0,points,path,follow=false,loaded=false,fetchedAt=0,metadata=new Map();
const colourMap=Object.fromEntries(Object.entries(categories).map(([key,c])=>[key,new THREE.Color(c.color)]));
$('#categoryLegend').innerHTML=Object.entries(categories).map(([key,c])=>`<span><i style="background:${c.color}"></i>${c.label}</span>`).join('');
const filterValues=()=>({type:$('#objectType').value,size:$('#objectSize').value,basis:$('#sizeBasis').value,estimates:$('#includeEstimates').checked});
function fail(message){$('#orbitError').hidden=false;$('#orbitError').textContent=message;}
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{fail('WebGL is unavailable. Enable hardware acceleration or use another browser for the 3D globe.');throw Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D Earth. Drag to rotate and scroll to zoom. Select a satellite using the search list.');
camera.position.set(2.7,1.9,3.6);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=1.18;controls.maxDistance=40;
const earth=new THREE.Mesh(new THREE.SphereGeometry(1,96,64),new THREE.MeshBasicMaterial({color:0x133e58}));scene.add(earth);
scene.add(new THREE.Mesh(new THREE.SphereGeometry(1.024,64,48),new THREE.MeshBasicMaterial({color:0x65b5db,transparent:true,opacity:.12,side:THREE.BackSide})));
const marker=new THREE.Mesh(new THREE.SphereGeometry(.014,14,10),new THREE.MeshBasicMaterial({color:0xffc775}));marker.visible=false;scene.add(marker);
function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);
async function drawEarth(){try{const response=await fetch('./orbit-data/land.json');if(!response.ok)throw Error();const geo=await response.json(),canvas=document.createElement('canvas');canvas.width=2048;canvas.height=1024;const c=canvas.getContext('2d');c.fillStyle='#0b263c';c.fillRect(0,0,2048,1024);c.strokeStyle='#1d4356';for(let x=0;x<=2048;x+=2048/12){c.beginPath();c.moveTo(x,0);c.lineTo(x,1024);c.stroke();}for(let y=0;y<=1024;y+=1024/6){c.beginPath();c.moveTo(0,y);c.lineTo(2048,y);c.stroke();}c.fillStyle='#327384';c.strokeStyle='#77bfc3';c.lineWidth=1.2;for(const f of geo.features){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polys){c.beginPath();for(const ring of poly){ring.forEach(([lon,lat],i)=>c[i?'lineTo':'moveTo']((lon+180)/360*2048,(90-lat)/180*1024));c.closePath();}c.fill('evenodd');c.stroke();}}const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;earth.material.color.set(0xffffff);earth.material.map=tex;earth.material.needsUpdate=true;}catch{$('#mapStatus').textContent='Coastlines unavailable; orbital calculations are unaffected.';}}drawEarth();
const currentTime=()=>paused?pausedAt:Date.now(),eligible=(item,time)=>Math.abs(time-item.epoch)<=14*86400000;
function filter(){const query=$('#satSearch').value.trim().toLowerCase(),group=$('#orbitFilter').value,time=currentTime();visible=items.map((p,i)=>({p,i})).filter(({p})=>eligible(p,time)&&(!query||`${p.name} ${p.id}`.toLowerCase().includes(query))&&(group==='all'||p.regime===group)&&matches(metadata.get(p.id),filterValues())).map(({i})=>i);$('#resultCount').textContent=`${visible.length.toLocaleString()} matching recent records · ${Math.min(80,visible.length)} listed`;$('#satResults').innerHTML=visible.slice(0,80).map(i=>`<button data-sat="${i}" aria-pressed="${i===selected}"><i class="category-dot" style="background:${categories[metadata.get(items[i].id)?.category||'unknown'].color}"></i>${esc(items[i].name)} <small>· ${esc(items[i].id)}</small></button>`).join('')||'<p>No recent records match. This source covers a subset of satellites.</p>';redraw();}
function redraw(){if(!coords||!points)return;pointIndexes=visible.filter(i=>valid[i]);const data=new Float32Array(pointIndexes.length*3),colours=new Float32Array(pointIndexes.length*3);pointIndexes.forEach((index,i)=>{data.set(coords.subarray(index*3,index*3+3),i*3);colourMap[metadata.get(items[index].id)?.category||'unknown'].toArray(colours,i*3);});points.geometry.setAttribute('color',new THREE.BufferAttribute(colours,3));points.geometry.setAttribute('position',new THREE.BufferAttribute(data,3));points.frustumCulled=false;$('#objectCount').textContent=pointIndexes.length.toLocaleString();$('#invalidCount').textContent=`${items.length-visible.length} records outside the current search, type, size, region or 14-day age limit. ${visible.length-pointIndexes.length} matching records cannot be propagated and are hidden.`;}
function choose(i){selected=i;const p=items[i];const m=metadata.get(p.id);$('#satCategory').textContent=categories[m?.category||'unknown'].label;$('#satCategory').style.color=categories[m?.category||'unknown'].color;$('#satDimensions').textContent='Body length: '+dimensionLabel(m)+' · Span: '+dimensionLabel(m,'span');$('#satMass').textContent='Catalogue dry mass: '+(m?.mass?m.mass+' kg'+(m.massEstimated?' (estimated)':''):'Unknown');$('#satMetaSource').textContent=m?'Classification and dimensions: GCAT / J. McDowell · '+m.jcat:'No matching GCAT metadata. Activity and size unknown.';$('#satName').textContent=p.name;$('#satIdentity').textContent=`NORAD ${p.id} · SatNOGS catalogue`;$('#satPeriod').textContent=p.period.toFixed(1)+' min';$('#satInclination').textContent=p.inclination.toFixed(2)+'°';$('#satEpoch').textContent='Orbital element epoch: '+new Date(p.epoch).toISOString().replace('T',' ');$('#sourceLink').href='https://db.satnogs.org/satellite/'+encodeURIComponent(p.row.sat_id)+'/';$('#sourceLink').hidden=false;$('#satProvider').textContent='Upstream source recorded by SatNOGS: '+String(p.row.tle_source||'Not specified');lastOrbit=0;filter();updateSelected(currentTime());}
function updateSelected(time){if(selected<0)return;const item=items[selected],p=eligible(item,time)&&position(item,time);if(!p||!visible.includes(selected)){marker.visible=false;if(path)path.visible=false;$('#satAltitude').textContent='Unavailable';$('#satSpeed').textContent='Unavailable';$('#satAge').textContent='Selected object is outside the current filters, or its position is unavailable.';return;}marker.visible=true;if(path)path.visible=true;marker.position.fromArray(p.xyz);$('#satAltitude').textContent=p.altitude.toFixed(0)+' km';$('#satSpeed').textContent=p.speed.toFixed(2)+' km/s';$('#satLatLon').textContent=`${p.lat.toFixed(2)}° latitude · ${p.lon.toFixed(2)}° longitude`;const age=(time-item.epoch)/86400000;$('#satAge').textContent=`Elements ${Math.abs(age).toFixed(2)} days ${age>=0?'old':'ahead of your clock'}. ${Math.abs(age)>3?'Older elements: increased uncertainty.':''}`;$('#satAge').classList.toggle('orbit-warning',Math.abs(age)>3);
 if(!lastOrbit||time-lastOrbit>=30000){lastOrbit=time;if(path){scene.remove(path);path.geometry.dispose();path.material.dispose();}const vectors=orbit(item,time).map(p=>new THREE.Vector3(...p));path=new THREE.Line(new THREE.BufferGeometry().setFromPoints(vectors),new THREE.LineBasicMaterial({color:0xffca77,transparent:true,opacity:.9}));scene.add(path);}if(follow)camera.position.copy(marker.position.clone().normalize().multiplyScalar(Math.max(2.3,marker.position.length()*1.7)));
}
function clearFilters(){ $('#satSearch').value='';$('#orbitFilter').value='all';$('#objectType').value='all';$('#objectSize').value='all';$('#includeEstimates').checked=true;filter();lastOrbit=0;}
$('#clearFilters').onclick=clearFilters;
for(const id of ['objectType','objectSize','sizeBasis','includeEstimates'])$('#'+id).onchange=()=>{filter();lastOrbit=0;};
$('#satSearch').oninput=filter;$('#orbitFilter').onchange=filter;$('#satResults').onclick=e=>{const b=e.target.closest('[data-sat]');if(b)choose(Number(b.dataset.sat));};
$('#pauseOrbit').onclick=()=>{paused=!paused;if(paused)pausedAt=Date.now();$('#pauseOrbit').textContent=paused?'Resume live':'Pause';lastTick=0;lastOrbit=0;};
$('#resetGlobe').onclick=()=>{follow=false;$('#focusSatellite').setAttribute('aria-pressed','false');$('#focusSatellite').textContent='Follow selected';camera.position.set(2.7,1.9,3.6);controls.target.set(0,0,0);controls.update();};
$('#focusSatellite').onclick=()=>{if(selected<0)return;follow=!follow;$('#focusSatellite').textContent=follow?'Stop following':'Follow selected';$('#focusSatellite').setAttribute('aria-pressed',String(follow));};
controls.addEventListener('start',()=>{follow=false;$('#focusSatellite').textContent='Follow selected';$('#focusSatellite').setAttribute('aria-pressed','false');});
const ray=new THREE.Raycaster();ray.params.Points.threshold=.018;let start;
renderer.domElement.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!points||!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const bounds=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1),camera);const hit=ray.intersectObject(points)[0],surface=ray.intersectObject(earth)[0];if(hit&&(!surface||hit.distance<surface.distance))choose(pointIndexes[hit.index]);});
async function load(){let data,fallback=false;$('#orbitStatus').textContent='Loading real satellite orbital elements…';try{const response=await fetch('https://raw.githubusercontent.com/AndreasPoimen/3rd-Year-Project/main/orbit-data/satnogs.json',{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();data=await response.json();}catch{fallback=true;const response=await fetch('./orbit-data/satnogs.json');if(!response.ok)throw Error('No catalogue snapshot available.');data=await response.json();}if(!Array.isArray(data.rows)||!data.rows.length)throw Error('Invalid catalogue file.');items=[];for(const row of data.rows){try{items.push(parseRow(row));}catch{}}if(!items.length)throw Error('No usable orbital elements.');fetchedAt=Date.parse(data.fetchedAt);$('#orbitStatus').textContent=`SatNOGS DB · ${items.length.toLocaleString()} real catalogue records · retrieved ${new Date(fetchedAt).toLocaleString()}${fallback?' · using bundled snapshot':''}.`;$('#coverageCount').textContent=`Only this source’s catalogue subset is included. ${items.filter(p=>eligible(p,Date.now())).length.toLocaleString()} records have epochs within 14 days; older records are not plotted.`;
 await loadMetadata();initExplorer({locate:id=>{const i=items.findIndex(p=>p.id===id);if(i>=0){clearFilters();choose(i);host.scrollIntoView({behavior:'smooth',block:'start'});}},canLocate:id=>{const i=items.findIndex(p=>p.id===id);return i>=0&&eligible(items[i],Date.now())&&!!position(items[i],Date.now());}});
 points=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({vertexColors:true,size:3,sizeAttenuation:false}));scene.add(points);worker=new Worker('./orbit-worker.js',{type:'module'});worker.onerror=()=>fail('The orbit calculator failed to start. Please refresh in a current browser.');worker.onmessage=({data})=>{busy=false;if(data.type==='ready'){lastTick=0;}else{coords=data.coordinates;valid=data.valid;redraw();}};busy=true;worker.postMessage({type:'load',rows:items.map(p=>p.row)});loaded=true;filter();const iss=items.findIndex(p=>p.id==='25544'&&eligible(p,Date.now()));const first=iss>=0?iss:items.findIndex(p=>eligible(p,Date.now()));if(first>=0)choose(first);}
function animate(frame){requestAnimationFrame(animate);if(document.hidden)return;const time=currentTime();$('#orbitClock').textContent=(paused?'PAUSED · ':'LIVE UTC · ')+new Date(time).toISOString().slice(0,19).replace('T',' ');if(loaded&&worker&&!busy&&(!lastTick||(!paused&&frame-lastTick>=1000))){lastTick=frame;busy=true;worker.postMessage({type:'tick',time});}if(frame-lastDetails>200){updateSelected(time);lastDetails=frame;if(fetchedAt){const age=(Date.now()-fetchedAt)/3600000;$('#catalogueAge').textContent=`Snapshot age: ${Math.max(0,age).toFixed(1)} hours. Scheduled refresh every 4 hours; refresh this page to load a newer snapshot.${age>12?' Update delayed: currently using older data.':''}`;$('#catalogueAge').classList.toggle('orbit-warning',age>12);}}controls.update();renderer.render(scene,camera);}
async function loadMetadata(){try{let data;try{const r=await fetch('https://raw.githubusercontent.com/AndreasPoimen/3rd-Year-Project/main/orbit-data/object-metadata.json',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();data=await r.json();}catch{const r=await fetch('./orbit-data/object-metadata.json');if(!r.ok)throw Error();data=await r.json();}metadata=new Map(data.rows.map(r=>[r.id,r]));$('#metadataStatus').textContent='GCAT classifications / dimensions available for '+items.filter(p=>metadata.has(p.id)).length.toLocaleString()+' orbital records · metadata retrieved '+new Date(data.fetchedAt).toLocaleString()+'. Remaining records have unknown type / size.';}catch{$('#metadataStatus').textContent='Classification data unavailable. Objects remain visible as unknown; size filters will have no known dimensions.';}}
requestAnimationFrame(animate);load().catch(e=>fail('Catalogue unavailable: '+e.message+' No simulated objects are shown.'));

const fullscreenButton=document.querySelector('#fullscreenGlobe');if(!document.fullscreenEnabled){fullscreenButton.hidden=true;}else{fullscreenButton.onclick=async()=>{try{if(document.fullscreenElement===host)await document.exitFullscreen();else await host.requestFullscreen();}catch{$('#mapStatus').textContent='Fullscreen was unavailable. You can still expand your browser window.';}};document.addEventListener('fullscreenchange',()=>{const active=document.fullscreenElement===host;fullscreenButton.textContent=active?'⛶ Exit fullscreen':'⛶ Fullscreen';fullscreenButton.setAttribute('aria-label',active?'Exit fullscreen globe':'Enter fullscreen globe');resize();});}
