'use strict';
(function(){
 const host=document.querySelector('#presentationStudio'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let decks=OrbitalCloud.getDecks(),active=decks[0]?.id,slideIndex=0,changed=false,showIndex=0;
 const selected=()=>decks.find(d=>d.id===active),sid=()=>crypto.randomUUID();
 const layoutNames={title:'Title / section',bullets:'Key points',split:'Two columns',process:'Process / sequence'};
 function slide(title='New slide',body='',layout='bullets'){return {id:sid(),layout,title,body,secondary:'',notes:'',source:''};}
 function saveFile(name,text,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 function message(t){document.querySelector('#studioFeedback').textContent=t;}
 function change(){changed=true;OrbitalCloud.markDirty();document.querySelector('#deckSave').textContent='Save presentation •';}
 function lines(s){return String(s||'').split('\n').map(s=>s.trim()).filter(Boolean);}
 function markup(s,index,total){const body=lines(s.body),secondary=lines(s.secondary);return `<article class="slide-canvas layout-${esc(s.layout)}"><div class="slide-brand">M.I.D.A.S.</div><h2>${esc(s.title)}</h2>${s.layout==='title'?`<p class="slide-lead">${esc(s.body)}</p>`:s.layout==='split'?`<div class="slide-columns"><ul>${body.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><ul>${secondary.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:s.layout==='process'?`<div class="slide-process">${body.map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${esc(x)}</p></div>`).join('')}</div>`:`<ul class="slide-points">${body.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}<div class="slide-foot"><span>${esc(s.source)}</span><span>${index+1} / ${total}</span></div></article>`;}
 function preview(){const d=selected(),s=d?.slides[slideIndex];if(!s)return;document.querySelector('#slidePreview').innerHTML=markup(s,slideIndex,d.slides.length);const count=lines(s.body).length;message(s.title.length>85||s.body.length>650||s.secondary.length>650||count>(s.layout==='process'?5:7)?'This slide is dense. Split the content across slides for readable presentation and export.':changed?'Unsaved edits — click Save presentation to share.':'Choose a layout, write your points, and present.');}
 function render(){if(changed)OrbitalCloud.markDirty();const d=selected();host.innerHTML=`<div class="deck-tools"><label>Presentation <select id="deckPicker">${decks.map(x=>`<option value="${esc(x.id)}" ${x.id===active?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><input type="search" id="slideSearch" aria-label="Search slides" placeholder="Find a word in these slides…"><button id="starterDeck">Create project update</button><label class="filebtn">Import deck JSON<input type="file" accept=".json" id="deckImport"></label></div><p id="studioFeedback" class="note" role="status"></p>${d?`<div class="deck-actions"><label>Deck name <input id="deckTitle" value="${esc(d.title)}" maxlength="120"></label><button id="deckSave" class="primary">Save presentation${changed?' •':''}</button><button id="presentDeck">▶ Present</button><button id="htmlExport">Export HTML / print PDF</button><button id="jsonExport">Export editable JSON</button><button id="deleteDeck" class="danger">Remove deck</button></div><div class="studio-grid"><div class="slide-rail"><button id="addSlide">＋ Add slide</button><div id="slideList">${d.slides.map((s,i)=>`<button class="slide-thumb ${i===slideIndex?'selected':''}" data-slide="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(s.title||'Untitled slide')}</strong><small>${esc(layoutNames[s.layout]||'Key points')}</small></button>`).join('')}</div></div><div class="slide-work"><div id="slidePreview"></div><div class="slide-actions"><button id="slideUp">← Move earlier</button><button id="slideDown">Move later →</button><button id="duplicateSlide">Duplicate</button><button id="removeSlide">Remove slide</button></div><form id="slideForm"><div class="row"><label>Layout<select id="slideLayout">${Object.entries(layoutNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Slide title<input id="slideTitle" maxlength="180"></label></div><div class="row"><label>Content · one point / step per line<textarea id="slideBody" rows="5" maxlength="3000"></textarea></label><label id="secondaryLabel">Second column<textarea id="slideSecondary" rows="5" maxlength="3000"></textarea></label></div><label>Source / footnote<input id="slideSource" maxlength="400"></label><label>Speaker notes<textarea id="slideNotes" rows="3" maxlength="5000"></textarea></label><p class="note">Notes are saved in editable JSON, but excluded from audience slides and HTML exports. Save shares the entire deck; simultaneous edits to the same deck may conflict.</p></form></div></div>`:'<div class="empty"><h2>Your next presentation starts here.</h2><p>Create a blank deck or a project update based on your current design.</p></div>'}`;
 document.querySelector('#starterDeck').onclick=()=>create(true);document.querySelector('#deckPicker').onchange=e=>{if(changed&&!confirm('Discard unsaved edits and switch presentations?')){e.target.value=active;return;}if(changed)decks=OrbitalCloud.getDecks();changed=false;active=e.target.value;slideIndex=0;render();};document.querySelector('#deckImport').onchange=importDeck;
 document.querySelector('#slideSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('[data-slide]').forEach(b=>b.hidden=!JSON.stringify(d?.slides[Number(b.dataset.slide)]).toLowerCase().includes(q));};
 if(!d)return;
 document.querySelector('#deckTitle').oninput=e=>{d.title=e.target.value;change();};document.querySelector('#deckSave').onclick=()=>{if(!d.title.trim()){message('Give this presentation a name.');return;}if(OrbitalCloud.saveDeck(d)){changed=false;document.querySelector('#deckSave').textContent='Save presentation';message('Queued for saving. Check the cloud status above.');}};
 document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{slideIndex=Number(b.dataset.slide);render();});
 document.querySelector('#addSlide').onclick=()=>{d.slides.push(slide());slideIndex=d.slides.length-1;changed=true;render();};
 document.querySelector('#duplicateSlide').onclick=()=>{d.slides.splice(slideIndex+1,0,{...structuredClone(d.slides[slideIndex]),id:sid()});slideIndex++;changed=true;render();};
 document.querySelector('#removeSlide').onclick=()=>{if(d.slides.length===1){message('Keep at least one slide.');return;}d.slides.splice(slideIndex,1);slideIndex=Math.min(slideIndex,d.slides.length-1);changed=true;render();};
 function move(delta){const n=slideIndex+delta;if(n<0||n>=d.slides.length)return;[d.slides[n],d.slides[slideIndex]]=[d.slides[slideIndex],d.slides[n]];slideIndex=n;changed=true;render();}
 document.querySelector('#slideUp').onclick=()=>move(-1);document.querySelector('#slideDown').onclick=()=>move(1);
 document.querySelector('#deleteDeck').onclick=()=>{if(!confirm('Remove this presentation for the team? Saved versions remain in History.'))return;if(OrbitalCloud.saveDeck(d,true)){decks=decks.filter(x=>x.id!==d.id);active=decks[0]?.id;slideIndex=0;changed=false;render();}};
 const s=d.slides[slideIndex];for(const [id,k] of [['slideLayout','layout'],['slideTitle','title'],['slideBody','body'],['slideSecondary','secondary'],['slideSource','source'],['slideNotes','notes']]){const el=document.getElementById(id);el.value=s[k]||'';el.oninput=()=>{s[k]=el.value;change();document.querySelector('#secondaryLabel').hidden=s.layout!=='split';preview();};}document.querySelector('#secondaryLabel').hidden=s.layout!=='split';document.querySelector('#slideForm').onsubmit=e=>e.preventDefault();
 document.querySelector('#jsonExport').onclick=()=>saveFile('MIDAS-presentation.json',JSON.stringify({version:1,deck:d},null,2),'application/json');document.querySelector('#htmlExport').onclick=()=>exportHTML(d);document.querySelector('#presentDeck').onclick=present;preview();}
 function create(template=false){if(changed){if(!confirm('Discard unsaved deck edits and start another? Save or export first if needed.'))return;decks=OrbitalCloud.getDecks();}const design=loadDesign(),d={id:'deck-'+sid(),title:template?'M.I.D.A.S. project update':'Untitled presentation',slides:template?[slide('M.I.D.A.S.','Material Identification and Debris Assimilation System','title'),slide('Project objectives',design.project.objectives,'bullets'),slide('Subsystems',design.subsystems.slice(0,5).map(s=>s.title).join('\n'),'process'),slide('Next decisions',design.project.questions,'bullets')]:[slide('Presentation title','Subtitle or main message','title')]};decks.push(d);active=d.id;slideIndex=0;changed=true;render();}
 function validDeck(d){return d&&typeof d.title==='string'&&d.title.length<=120&&Array.isArray(d.slides)&&d.slides.length>0&&d.slides.length<=100&&d.slides.every(s=>s&&Object.hasOwn(layoutNames,s.layout)&&['title','body','secondary','notes','source'].every(k=>typeof s[k]==='string'&&s[k].length<=5000));}
 async function importDeck(e){try{if(changed&&!confirm('Discard unsaved deck edits and import another?'))return;const f=e.target.files[0];if(!f)return;if(f.size>900000)throw Error('Keep deck files below 900 KB.');const obj=JSON.parse(await f.text()),d=obj.deck;if(!validDeck(d))throw Error('Choose a MIDAS deck JSON export (up to 100 slides).');d.id='deck-'+sid();d.slides.forEach(s=>s.id=sid());decks.push(d);active=d.id;slideIndex=0;changed=true;render();}catch(err){message(err.message);}}
 const modal=document.createElement('dialog');modal.id='presentationView';modal.innerHTML='<div id="audienceSlide"></div><div class="presentation-controls"><button id="showPrev">← Previous</button><button id="showNext">Next →</button><button id="showClose">Exit presentation</button></div>';document.body.append(modal);
 function show(){const d=selected();document.querySelector('#audienceSlide').innerHTML=markup(d.slides[showIndex],showIndex,d.slides.length);}
 function present(){showIndex=0;show();modal.showModal();}
 document.querySelector('#showPrev').onclick=()=>{showIndex=Math.max(0,showIndex-1);show();};document.querySelector('#showNext').onclick=()=>{showIndex=Math.min(selected().slides.length-1,showIndex+1);show();};document.querySelector('#showClose').onclick=()=>modal.close();modal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();document.querySelector('#showNext').click();}if(e.key==='ArrowLeft'){e.preventDefault();document.querySelector('#showPrev').click();}});
 async function exportHTML(d){try{const r=await fetch('presentations.css');if(!r.ok)throw Error('Unable to load slide styles');const css=await r.text();const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(d.title)+'</title><style>'+css+'</style><body class="exported-deck"><nav class="export-controls"><button onclick="window.print()">Print / Save as PDF</button><span>Scroll through slides. Use landscape, no margins and background graphics for PDF.</span></nav>'+d.slides.map((s,i)=>markup(s,i,d.slides.length)).join('')+'</body></html>';saveFile('MIDAS-presentation.html',html,'text/html');message('HTML exported. Open it in your browser to present or Print / Save as PDF.');}catch(e){message(e.message);}}
 document.querySelector('#newDeck').onclick=()=>create();window.MidasPresentations={exportAll:()=>structuredClone(decks),refresh:()=>{decks=OrbitalCloud.getDecks();if(!decks.some(d=>d.id===active))active=decks[0]?.id;slideIndex=Math.min(slideIndex,(selected()?.slides.length||1)-1);changed=false;render();}};render();
})();
