(function(root){
 'use strict';
 const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
 function doi(input){let s=String(input||'').trim();try{s=decodeURIComponent(s);}catch{}return (s.match(/10\.\d{4,9}\/[^\s?#<>"]+/i)||[])[0]?.replace(/[.,;]+$/,'')||'';}
 function url(input){let s=String(input||'').trim();if(!s)return '';if(/^doi:\s*/i.test(s))s=s.replace(/^doi:\s*/i,'');if(/^10\.\d{4,9}\//.test(s))return 'https://doi.org/'+s;if(!/^[a-z][a-z\d+.-]*:/i.test(s))s='https://'+s;try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)&&u.hostname.includes('.')?u.href:'';}catch{return '';}}
 function authors(p){if(Array.isArray(p.authorList)&&p.authorList.length)return p.authorList.map(a=>typeof a==='string'?a:[a.family,a.given].filter(Boolean).join(', '));return clean(p.authors).split(/\s*;\s*|\s+and\s+/).filter(Boolean);}
 function tex(s){const map={'\\':'\\textbackslash{}','{':'\\{','}':'\\}','&':'\\&','%':'\\%','$':'\\$','#':'\\#','_':'\\_','~':'\\textasciitilde{}','^':'\\textasciicircum{}'};return clean(s).replace(/[\\{}&%$#_~^]/g,c=>map[c]);}
 function citeKey(p){const a=authors(p)[0]||'Source',base=(a.split(',')[0].split(' ').pop()||'Source').normalize('NFD').replace(/[^a-zA-Z]/g,'')||'Source';let hash=2166136261;for(const ch of String(p.id||p.url||p.title)){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619);}return base+(String(p.year||'nd'))+(hash>>>0).toString(36).slice(0,6);}
 function reference(p){const names=authors(p).join('; ')||'Author not recorded',d=doi(p.doi)||doi(p.url);return `${names} (${p.year||'n.d.'}). ${clean(p.title)}.${p.journal?' '+clean(p.journal)+'.':''}${p.volume?' '+clean(p.volume)+(p.issue?'('+clean(p.issue)+')':'')+'.':''}${p.pages?' pp. '+clean(p.pages)+'.':''}${p.publisher?' '+clean(p.publisher)+'.':''}${d?' https://doi.org/'+d:p.url?' '+url(p.url):''}`;}
 function bibtex(p){const type=['article','inproceedings','book','techreport','misc'].includes(p.entryType)?p.entryType:p.journal?'article':'misc';const fields={title:'{'+tex(p.title)+'}',author:authors(p).map(tex).join(' and '),year:p.year,journal:p.journal,booktitle:p.booktitle,publisher:p.publisher,volume:p.volume,number:p.issue,pages:p.pages,doi:doi(p.doi)||doi(p.url),url:url(p.url)};return '@'+type+'{'+citeKey(p)+',\n'+Object.entries(fields).filter(([,v])=>v).map(([k,v])=>'  '+k+' = {'+(['title','author'].includes(k)?v:tex(v))+'}').join(',\n')+'\n}';}
 const api={doi,url,authors,tex,citeKey,reference,bibtex};root.MidasReferences=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
