'use strict';
(async function(){
 const host=document.querySelector('#teamContent'),client=OrbitalCloud.teamClient(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(OrbitalCloud.role()!=='owner'){host.innerHTML='<div class="empty">Only the project owner can manage membership.</div>';return;}
 let requests=[],members=[],filter='pending';
 async function load(){host.innerHTML='<p role="status">Loading team requests…</p>';try{const all=[];for(let start=0;;start+=500){const {data,error}=await client.from('of_access_requests').select('*').order('requested_at',{ascending:false}).range(start,start+499);if(error)throw error;all.push(...data);if(data.length<500)break;}const {data,error}=await client.from('of_team').select('user_id,email,role');if(error)throw error;requests=all;members=data;render();}catch(e){host.innerHTML='<div class="panel"><h2>Team setup required</h2><p>'+esc(e.message)+'</p><p>Run the supplied 02-team-approval.sql in Supabase SQL Editor, then reload this page.</p></div>';}}
 function render(){const counts=k=>requests.filter(r=>r.status===k).length;host.innerHTML=`<div class="notice">Approve people you recognise from your team. Email addresses are self-declared in the free password-registration flow. Approval is permanent until you revoke it; logging out does not reset it.</div><div class="team-filters">${['pending','approved','rejected','revoked','all'].map(k=>`<button data-filter="${k}" class="${filter===k?'primary':''}">${k[0].toUpperCase()+k.slice(1)} ${k==='all'?requests.length:counts(k)}</button>`).join('')}<button id="refreshTeam">Refresh</button><input id="teamSearch" type="search" placeholder="Search name or email" aria-label="Search team"></div><p id="teamFeedback" role="status"></p><div class="team-list">${requests.filter(r=>filter==='all'||r.status===filter).map(r=>{const m=members.find(m=>m.user_id===r.user_id);return `<article class="panel team-member" data-name="${esc((r.display_name+' '+r.email).toLowerCase())}"><div><h3>${esc(r.display_name)}</h3><p>${esc(r.email)}</p><span class="tag">${esc(r.status)}${m?' · '+esc(m.role):''}</span><p class="note">Requested ${esc(new Date(r.requested_at).toLocaleString())}</p>${r.note?`<p>${esc(r.note)}</p>`:''}</div><div class="team-actions">${m?.role==='owner'?'<p class="note">Owner account · protected</p>':`<label>Access level<select data-role="${r.user_id}" aria-label="Role for ${esc(r.email)}"><option value="viewer" ${m?.role==='viewer'?'selected':''}>Viewer · read only</option><option value="editor" ${m?.role==='editor'?'selected':''}>Editor · edit project</option></select></label><button data-id="${r.user_id}" data-decision="approve" class="primary">${r.status==='approved'?'Update role':'Approve access'}</button>${r.status==='approved'?`<button data-id="${r.user_id}" data-decision="revoke" class="danger">Revoke access</button>`:r.status==='pending'?`<button data-id="${r.user_id}" data-decision="reject">Reject request</button>`:''}`}</div></article>`;}).join('')||'<div class="empty">No accounts in this category.</div>'}</div>`;
 host.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});document.querySelector('#refreshTeam').onclick=load;document.querySelector('#teamSearch').oninput=e=>host.querySelectorAll('[data-name]').forEach(a=>a.hidden=!a.dataset.name.includes(e.target.value.toLowerCase()));
 host.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,decision=b.dataset.decision,record=requests.find(r=>r.user_id===id),role=host.querySelector(`[data-role="${id}"]`).value;const check=decision+role;if(b.dataset.confirm!==check){b.dataset.confirm=check;b.textContent='Confirm '+(decision==='approve'?'approval as '+role:decision);document.querySelector('#teamFeedback').textContent='Confirm '+decision+' for '+record.email+'. Refresh or choose a category to cancel.';return;}host.querySelectorAll('button').forEach(el=>el.disabled=true);const {error}=await client.rpc('of_review_access',{p_user_id:id,p_decision:decision,p_role:role});if(error){host.querySelectorAll('button').forEach(el=>el.disabled=false);document.querySelector('#teamFeedback').textContent=error.message;}else await load();});
 }
 await load();
})();
